### ISSUE TITLE
RSA maximum message size ignores modulus

### ISSUE THREAD

**Issue by kaikuchn** [garyf/json_web_token#4]
The RSA module defines a [constant](https://github.com/garyf/json_web_token/blob/master/lib/json_web_token/algorithm/rsa.rb#L14) `MESSAGE_BYTES_MAX` irrespective of the RSA modulus size.

The referenced RFC states that the maximum should be `modulus - 11` octets, i.e., when I use a 4096 bit key I'd expect the maximum message size to be 501 octets. Or did I get that wrong?

**Comment by kaikuchn** [comment]
I'm also confused why the payload size has to be below `MESSAGE_BYTES_MAX`. Isn't the payload run through `SHA2` before being signed? And that size is always fixed, depending on the chosen number of bits.

**Comment by garyf** [comment]
agree; addressed by 1b4dc0d; thank you @kaikuchn
